
<!DOCTYPE html>
<html>
<head>
    <title>This Email generated by Interview Management Systsem</title>
</head>
<body>
    <h1>{{ $user['name'] }}</h1>
    <p>{{ $user['info'] }}</p>
    <p>Dear {{ $user['name'] }}  </p>
    <p>you are assigned interview at {{ $user['info'] }} </p>
    <p>Thank you</p>
</body>
</html> 