
<!DOCTYPE html>
<html>
<head>
    <title>This Email generated by Interview Management Systsem</title>
</head>
<body>
  <div class="container">
    <p>Dear {{ $user['name'] }}  </p>
    <p>you are assigned an interview at {{ $user['info'] }} </p>
    <p>make sure to be on time</p>
    <p>Thank you</p>
  </div>
</body>
</html>
